Q1="SELECT Player.player_id,Player.team_id,Player.jersey_no,Player.name,Player.date_of_birth,Player.age FROM Player INNER JOIN MatchCaptain ON Player.player_id=MatchCaptain.captain AND Player.team_id=MatchCaptain.team_id WHERE Player.player_id NOT IN (SELECT Goaldetails.player_id FROM GoalDetails)"
Q2="SELECT team_id,COUNT(team_id) AS no_of_games FROM MatchTeamDetails GROUP BY team_id" 
Q3="SELECT team_id,COUNT(goal_id)*1.0/(SELECT COUNT(player_id) FROM Player GROUP BY team_id) AS avg_goal_score FROM GoalDetails GROUP BY team_id"
Q4="SELECT captain,COUNT(captain) AS no_of_times_captain FROM MatchCaptain GROUP BY captain"
Q5="SELECT COUNT(DISTINCT captain) AS no_of_players FROM MatchCaptain INNER JOIN Match ON MatchCaptain.match_no=Match.match_no WHERE MatchCaptain.captain=Match.player_of_match"
Q6="SELECT DISTINCT captain FROM MatchCaptain WHERE EXISTS(SELECT player_id FROM Player WHERE MatchCaptain.captain=Player.player_id) AND NOT EXISTS (SELECT player_of_match FROM Match WHERE MatchCaptain.captain=Match.player_of_match)"
Q7="SELECT strftime('%m',play_date),COUNT(strftime('%m',play_date)) AS no_of_matches FROM Match GROUP BY strftime('%m',play_date) ORDER BY COUNT(strftime('%m',play_date)) DESC"
Q8="SELECT jersey_no,COUNT(jersey_no) AS no_captains FROM Player INNER JOIN MatchCaptain ON Player.player_id=MatchCaptain.captain GROUP BY jersey_no ORDER BY COUNT(jersey_no) DESC,jersey_no DESC"
Q9="SELECT player_id,AVG(audience) FROM Player INNER JOIN MatchTeamDetails ON Player.team_id=MatchTeamDetails.team_id INNER JOIN Match ON Match.match_no=MatchTeamDetails.match_no GROUP BY player_id ORDER BY AVG(audience) DESC,player_id DESC"
Q10="SELECT team_id,AVG(age) FROM Player GROUP BY team_id"
Q11="SELECT AVG(age) AS avg_age_of_captains FROM Player INNER JOIN MatchCaptain ON Player.player_id=MatchCaptain.captain"
Q12="SELECT strftime('%m',date_of_birth),COUNT(strftime('%m',date_of_birth)) AS no_of_players FROM Player GROUP BY strftime('%m',date_of_birth) ORDER BY COUNT(strftime('%m',date_of_birth)) DESC,strftime('%m',date_of_birth) DESC"  
Q13="SELECT captain,COUNT(captain) AS no_of_wins FROM MatchCaptain INNER JOIN MatchTeamDetails ON MatchCaptain.match_no=MatchTeamDetails.match_no WHERE MatchTeamDetails.win_lose='W' AND MatchCaptain.team_id=MatchTeamDetails.team_id GROUP BY MatchCaptain.captain ORDER BY COUNT(captain) DESC"
