Q1="SELECT COUNT(id) FROM Movie WHERE year<2000"
Q2="SELECT AVG(rank) FROM Movie WHERE year=1991"
Q3="SELECT MIN(rank) FROM Movie WHERE year=1991"
Q4="SELECT fname,lname FROM Actor INNER JOIN Cast ON id=pid WHERE mid=27"
Q5="SELECT COUNT(mid) FROM Cast INNER JOIN Actor ON id=pid WHERE fname='Jon' AND lname='Dough'"
Q6="SELECT name FROM Movie WHERE name LIKE 'Young Latin Girls%' AND (year BETWEEN 2003 AND 2006)"
Q7="SELECT fname,lname FROM Director INNER JOIN MovieDirector ON Director.id=MovieDirector.did INNER JOIN Movie ON Movie.id=MovieDirector.mid WHERE name LIKE 'Star Trek%' GROUP BY MovieDirector.did HAVING COUNT(name)>=1"
Q8="SELECT name FROM Movie INNER JOIN Cast ON `Movie`.id=`Cast`.mid INNER JOIN Actor ON `Actor`.id=`Cast`.pid INNER JOIN MovieDirector ON `MovieDirector`.mid=`Movie`.id INNER JOIN Director ON `MovieDirector`.did=`Director`.id WHERE (`Director`.fname='Jackie (I)' AND `Director`.lname='Chan') AND (`Actor`.fname='Jackie (I)' AND `Actor`.lname='Chan') ORDER BY `Movie`.name"
Q9="SELECT fname,lname FROM Director INNER JOIN MovieDirector ON Director.id=MovieDirector.did INNER JOIN Movie ON Movie.id=MovieDirector.mid WHERE year=2001 GROUP BY MovieDirector.did HAVING COUNT(mid)>=4 ORDER BY fname ASC,lname DESC"
Q10="SELECT gender,COUNT(gender) FROM Actor GROUP BY gender ORDER BY GENDER ASC"
Q11="SELECT a.name,b.name,a.rank,a.year FROM Movie a INNER JOIN Movie b ON a.name!=b.name AND a.year=b.year AND a.rank=b.rank ORDER BY a.name Limit 100;"
Q12="SELECT fname,year,AVG(rank) FROM Actor INNER JOIN Cast ON `Actor`.id=`Cast`.pid INNER JOIN Movie ON `Movie`.id=`Cast`.mid GROUP BY 'Actor'.id,year ORDER BY fname ASC,year DESC Limit 100"
Q13="SELECT `Actor`.fname,`Director`.fname,AVG(rank) FROM Actor INNER JOIN Cast ON `Actor`.id=`Cast`.pid INNER JOIN Movie ON `Movie`.id=`Cast`.mid INNER JOIN  MovieDirector ON  `MovieDirector`.mid=`Movie`.id INNER JOIN Director ON `Director`.id=`MovieDirector`.did GROUP BY `Actor`.id,`MovieDirector`.did HAVING COUNT(`MovieDirector`.did)>=5 ORDER BY AVG(rank) DESC,`Director`.fname ASC,`Actor`.fname DESC Limit 100" 